version: 2
jobs:
  build:
    docker:
      - image: circleci/golang
    working_directory: /go/src/github.com/eripe970/pubsub-signing
    steps:
      - checkout
      - run: go get -v -t ./...
      - run: go vet ./...
      - run: go test -v -race ./...
